version: '3.3'

services:
  postgres:
    image: postgres
    volumes:
      - ezybucks_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ezybucks
    ports:
      - "5432:5432"

volumes:
  ezybucks_data:
